import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Admin',
      email: 'admin@example.com',
      password: bcrypt.hashSync('12345'),
    },
  ],
  products: [
    {
      name: 'productA-name',
      category: 'Pharma',
      description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eaque, rerum eos? Libero deleniti incidunt magnam obcaecati eaque hic consectetur eius?',
      price: 100,
      token: 'productA-token',
      brand: 'Teva',
      countInStock: 0,
      rating: 2.5,
      numReviews: 100,
      image: '/images/p1.jpg',
    },
    {
      name: 'productB-name',
      category: 'Pharma',
      description: 'Lorem ipsum? Libero deleniti incidunt eaque hic consectetur eius?',
      price: 70,
      token: 'productB-token',
      brand: 'Teva',
      countInStock: 3,
      rating: 3,
      numReviews: 95,
      image: '/images/p2.jpg',
    },
    {
      name: 'productC-name',
      category: 'Pharma',
      description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit.',
      price: 10,
      token: 'productC-token',
      brand: 'Teva',
      countInStock: 24,
      rating: 4,
      numReviews: 120,
      image: '/images/p3.jpg',
    },
    {
      name: 'productD-name',
      category: 'Pharma',
      description: 'Lorem ipsum,Eaque, rerum eos? Libero deleniti incidunt magnam obcaecati eaque hic consectetur eius?',
      price: 110,
      token: 'productD-token',
      brand: 'Teva',
      countInStock: 7,
      rating: 4.5,
      numReviews: 80,
      image: '/images/p4.jpg',
    },
    {
      name: 'productE-name',
      category: 'Pharma',
      description: 'bla bla...',
      price: 100,
      token: 'productE-token',
      brand: 'Teva',
      countInStock: 6,
      rating: 2.5,
      numReviews: 100,
      image: '/images/p5.jpg',
    },
    {
      name: 'productF-name',
      category: 'Pharma',
      description: 'ddddd sdfskdf fjskdhfk jkhskdhgf',
      price: 70,
      token: 'productF-token',
      brand: 'Teva',
      countInStock: 3,
      rating: 3,
      numReviews: 95,
      image: '/images/p6.jpg',
    },
    {
      name: 'productG-name',
      category: 'Pharma',
      description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eaque, rerum eos? Libero deleniti incidunt magnam obcaecati eaque hic consectetur eius?',
      price: 10,
      token: 'productG-token',
      brand: 'Teva',
      countInStock: 24,
      rating: 4,
      numReviews: 120,
      image: '/images/p7.jpg',
    },
    {
      name: 'productH-name',
      category: 'Pharma',
      description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eaque, rerum eos? Libero deleniti eius?',
      price: 110,
      token: 'productH-token',
      brand: 'Teva',
      countInStock: 7,
      rating: 4.5,
      numReviews: 80,
      image: '/images/p8.jpg',
    },
  ],
};

export default data;
